name: Deploy

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  pull_request:
    branches:
      - main  # or master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install and Build
        run: |
          npm cache clean --force
          npm ci
          npm install @rollup/rollup-linux-x64-gnu
          npm run build 